const KEY="fitnessQuest.v1",D={xp:0,startWeight:185,goalWeight:170,tripName:"Hawaii",targetDate:"2027-06-01",weeklyGoal:4,weights:[],events:[],reminderTime:"18:00",intensity:"Make Me Do It"};let s;try{s={...D,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{s={...D}}
const info={
"Band squats":["Stand on the middle of the band with feet about shoulder-width apart. Hold the handles near your shoulders.","Brace your abdomen, send your hips slightly back, bend your knees and lower under control. Keep your whole foot planted, then stand by pushing the floor away.","Quads and glutes.","Knees collapsing inward, heels lifting, rounding your back, or resistance that makes you lose control."],
"Bent-over band rows":["Stand on the middle of the band with both feet about hip-width apart. Hold a handle in each hand and hinge at your hips until your torso is angled forward comfortably.","Keep your neck neutral and torso still. Pull your elbows toward your hips/ribs, pause briefly, then lower the handles slowly.","Mid/upper back, lats, and the muscles around your shoulder blades.","Shrugging, rounding your back, standing up to create momentum, or yanking the band."],
"Band Romanian deadlifts":["Stand on the band with feet about hip-width apart and hold the handles at your sides.","Keep a soft knee bend and push your hips backward while keeping your back comfortable and long. Stop at a strong hamstring stretch, squeeze your glutes and stand.","Hamstrings and glutes.","Turning it into a squat, rounding to reach lower, or leaning backward at the top."],
"Band pull-aparts":["Hold a light band in front of you around chest/shoulder height with hands wider than shoulder width.","Keep your ribs relaxed and pull the band apart under control. Pause, then return slowly.","Rear shoulders and upper back.","Shrugging, arching your lower back, forcing the range, or using too much resistance."],
"Band-around-back chest press":["Run the middle of the band across your upper back, below your neck, and bring the handles forward under your arms. Use a staggered stance for balance.","Brace your trunk and press both hands forward until your arms are nearly straight, then return slowly while keeping tension on the band.","Chest, front shoulders, and triceps.","Putting the band across your neck, arching your lower back, shrugging, or letting the band snap back."],
"Band overhead press":["Stand on the band and bring the handles to shoulder height.","Brace your trunk and press overhead without leaning backward. Lower under control.","Shoulders and triceps.","Overarching your back, shrugging excessively, or using resistance that forces you to lean."],
"Band split squat":["Take a comfortable staggered stance. If using the band, place it under the front foot with handles at your shoulders.","Lower straight down by bending both knees while balancing through the front foot, then push through the front foot to rise.","Front-leg quad and glute.","A stance too narrow to balance or letting the front knee collapse inward."],
"Dead bug":["Lie on your back with hips and knees bent about 90 degrees and arms pointing upward.","Brace gently. Slowly lower the opposite arm and leg while keeping your torso controlled, return, then alternate.","Abdominals working to keep your trunk still.","Rushing, holding your breath, or extending farther than you can control."],
"Band glute bridge":["Lie on your back with knees bent and feet flat. A loop band can sit just above your knees if available.","Brace lightly, squeeze your glutes and lift your hips to a comfortable straight line. Pause and lower slowly.","Glutes, with some hamstrings.","Overarching your lower back or trying to lift higher than your hips comfortably allow."],
"Band reverse flys":["Stand on the middle of a light band and hinge forward slightly with a soft bend in your knees. Cross the handles if that gives you a better line of pull.","With a small bend in your elbows, open your arms out and slightly back until you feel your rear shoulders and upper back working, then return slowly.","Rear shoulders and upper back.","Shrugging, swinging your torso, locking your elbows, or using so much resistance that you cannot move smoothly."]
};
const plans=[["A · Pull + Legs","Band squats · 3 × 12","Bent-over band rows · 3 × 12","Band Romanian deadlifts · 3 × 12","Band pull-aparts · 2 × 15"],["B · Push + Core","Band-around-back chest press · 3 × 12","Band overhead press · 3 × 10","Band split squat · 2 × 10/side","Dead bug · 2 × 8/side"],["C · Pull + Legs","Band squats · 3 × 12","Bent-over band rows · 3 × 12","Band glute bridge · 3 × 15","Band reverse flys · 2 × 15"],["D · Full Body","Band-around-back chest press · 3 × 12","Bent-over band rows · 3 × 12","Band Romanian deadlifts · 3 × 12","Band pull-aparts · 2 × 15"]];
const posture=[["Chin tucks","5 slow reps","Look straight ahead and gently slide your head backward as if making a small double chin. Do not tilt up or down. Hold 2–3 seconds."],["Doorway pec stretch","30 sec / side","Put your forearm on a doorframe with your elbow around shoulder height or slightly lower. Step forward gently until you feel a comfortable chest stretch. Do not force the shoulder backward."],["Band pull-aparts","10–15 reps","Use a light band. Keep your ribs relaxed and pull apart under control. Let the upper back do the work."],["Bent-over band rows","10–12 reps","Use light resistance. Stand on the band, hinge forward comfortably, keep your neck neutral, and pull your elbows toward your ribs. Return slowly without swinging."],["Wall slides","8 slow reps","Stand with your back near a wall. Keep your ribs from flaring and slide your arms upward only as far as comfortable. Do not force your hands or back flat."]];
const q=x=>document.querySelector(x),today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`},ws=()=>{let d=new Date(),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(0,0,0,0);return d},we=t=>s.events.filter(e=>e.type===t&&new Date(e.date+"T12:00:00")>=ws());
function base(x){return Object.keys(info).find(k=>x.startsWith(k))}
function guide(x){let k=base(x),d=info[k];return d?`<details class="guide"><summary>How to do it</summary><p><b>Setup:</b> ${d[0]}</p><p><b>Movement:</b> ${d[1]}</p><p><b>You should feel:</b> ${d[2]}</p><p><b>Avoid:</b> ${d[3]}</p><p class="small"><b>Resistance:</b> The final 2–3 reps should feel challenging while your form stays controlled.</p></details>`:""}
function save(){localStorage.setItem(KEY,JSON.stringify(s));render()}function log(t,x){if(s.events.some(e=>e.type===t&&e.date===today()))return false;s.events.push({type:t,date:today(),xp:x});s.xp+=x;save();return true}
function render(){let w=we("workout").length,p=we("posture").length,latest=s.weights.length?s.weights[s.weights.length-1].weight:s.startWeight,plan=plans[Math.min(w,3)];q("#workouts").textContent=`${w} / ${s.weeklyGoal}`;q("#postures").textContent=`${p} / 5`;q("#xp").textContent=s.xp;q("#level").textContent=`Level ${Math.floor(s.xp/500)+1}`;q("#weight").textContent=latest;let t=new Date(s.targetDate+"T12:00:00");q("#days").textContent=Math.max(0,Math.ceil((t-new Date())/86400000))+" days";q("#trip").textContent=`${s.tripName.toUpperCase()} · ${t.toLocaleDateString(undefined,{month:"short",year:"numeric"}).toUpperCase()}`;q("#exerciseList").innerHTML=plan.slice(1).map((x,i)=>`<div class="exercise"><div class="exerciseHead"><input type="checkbox" id="e${i}"><label for="e${i}"><b>${base(x)}</b><div class="muted small">${x.slice(base(x).length+3)}</div></label></div>${guide(x)}</div>`).join("");q("#start").textContent=s.startWeight;q("#goalView").textContent=s.goalWeight;let den=s.startWeight-s.goalWeight;q("#bar").style.width=(den>0?Math.max(0,Math.min(100,(s.startWeight-latest)/den*100)):0)+"%";q("#goal").value=s.goalWeight;q("#tripName").value=s.tripName;q("#targetDate").value=s.targetDate;q("#weeklyGoal").value=s.weeklyGoal;q("#reminderTime").value=s.reminderTime;q("#intensity").value=s.intensity;q("#history").innerHTML=s.weights.length?s.weights.slice().reverse().slice(0,8).map(x=>`<div class="exercise"><b>${x.weight} lb</b>${x.waist?` · ${x.waist}" waist`:""}<div class="muted small">${x.date}</div></div>`).join(""):"No check-ins yet."}
q("#program").innerHTML=plans.map(p=>`<h3>Workout ${p[0]}</h3>${p.slice(1).map(x=>`<div class="exercise"><div class="exerciseHead"><span>•</span><span>${x}</span></div>${guide(x)}</div>`).join("")}`).join("");q("#postureRoutine").innerHTML=posture.map((x,i)=>`<div class="postureStep"><b>${i+1}. ${x[0]}</b> · <span class="muted">${x[1]}</span><details class="guide"><summary>Instructions</summary><p>${x[2]}</p></details></div>`).join("");
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("main section").forEach(x=>x.hidden=x.id!==b.dataset.tab);document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));render()});
q("#complete").onclick=()=>alert(log("workout",100)?"Workout complete. +100 XP":"Full workout already logged today.");q("#posture").onclick=()=>alert(log("posture",25)?"Posture reset logged. +25 XP":"Already logged today.");q("#rescue").onclick=()=>alert(log("rescue",40)?"You showed up. +40 XP":"Rescue already logged today.");q("#rescueGo").onclick=()=>q('[data-tab="workout"]').click();
q("#weightForm").onsubmit=e=>{e.preventDefault();let weight=+q("#weightInput").value,waist=+q("#waistInput").value||null;s.weights.push({date:today(),weight,waist});e.target.reset();save()};
q("#saveSettings").onclick=()=>{s.goalWeight=+q("#goal").value||170;s.tripName=q("#tripName").value.trim()||"Hawaii";s.targetDate=q("#targetDate").value||"2027-06-01";s.weeklyGoal=Math.max(1,Math.min(7,+q("#weeklyGoal").value||4));s.reminderTime=q("#reminderTime").value;s.intensity=q("#intensity").value;save();alert("Settings saved.")};
q("#enable").onclick=async()=>{if(!("Notification"in window)){q("#notifyStatus").textContent="Notifications unsupported here.";return}let p=await Notification.requestPermission();q("#notifyStatus").textContent=p==="granted"?"Permission granted. Ready for push-backend setup.":"Permission: "+p};
q("#test").onclick=async()=>{if(!("Notification"in window)||Notification.permission!=="granted")return alert("Enable notifications first.");let r=await navigator.serviceWorker.ready;r.showNotification("Fitness Quest",{body:"Today's quest is ready. The 5-minute version counts.",icon:"icon.svg"})};
q("#export").onclick=()=>{let a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:"application/json"}));a.href=u;a.download=`fitness-quest-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
q("#import").onchange=async e=>{try{s={...D,...JSON.parse(await e.target.files[0].text())};save();alert("Backup imported.")}catch{alert("Could not read backup.")}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=1.1.2",{updateViaCache:"none"});render();